### ISSUE TITLE
Created quest -> map doesn't load

### ISSUE THREAD

**Issue by GentlestudentAHS** [oSoc19/gentlestudent-mobile#17]
Created a Quest and that flow seems to work, but now the map doesn't load anymore.

**Comment by BramDC3** [comment]
The map doesn't load anymore because there is a bad address in the Firebase, presumably an address added via the website

**Comment by BramDC3** [comment]
The bad addresses have a latitude and longitude that was either a String or null, if it's a String it will be parsed now
